apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: weather-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapi
  template:
    metadata:
      labels:
        app: weather-forecast
        service: webapi
    spec:
      containers:
        - name: webapi
          image: mxshdh/demo-kubernetes-deployment:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 81
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:81
---
apiVersion: v1
kind: Service
metadata:
  name: webapi
  labels:
    app: weather-forecast
    service: webapi
spec:
  type: NodePort
  ports:
    - port: 81
      targetPort: 81
      nodePort: 32222
      protocol: TCP
  selector:
    service: webapi